### ISSUE TITLE
<tabs-clab> Tabs first content cut off from dom when is inside a dom-repeat

### ISSUE THREAD

**Issue by equinusocio** [contactlab/contactlab-ui-components#130]
The `<tabs-clab>` component cut off the first `.tab-content`  div when is inside a `dom-repeat` element, each template iteration. **The issue is present only on Chrome** but if you put a `<div>` element as a wrapper outside the `dom-repeat` it work.

Not working example:
```html
<template is="dom-repeat" items="{{items}}">
  <tabs-clab labels='["Tab 1", "Tab 2", "Tab 3"]'>
     <div class="tab-content">Tab 1 content</div> <!-- First content is cut off each iteration -->
     <div class="tab-content">Tab 2 content</div>
     <div class="tab-content">Tab 3 content</div>
  </tabs-clab>
</template>
```

Working example:
```html
<div>
  <template is="dom-repeat" items="{{items}}">
    <tabs-clab labels='["Tab 1", "Tab 2", "Tab 3"]'>
       <div class="tab-content">Tab 1 content</div>
       <div class="tab-content">Tab 2 content</div>
       <div class="tab-content">Tab 3 content</div>
    </tabs-clab>
  </template>
</div>
```

@LasaleFamine think this can be the "issue".
```js
attached() {
    this._content = this.getEffectiveChildren();
}
```

**Comment by moebiusmania** [comment]
we will keep extra attention on this while rewriting for Orkestra Elements

**Comment by LasaleFamine** [comment]
A solution could be just don't handle the "content", like the [paper-tabs](https://www.webcomponents.org/element/PolymerElements/paper-tabs) element and maybe use another element to handle the content ([paper-tab](https://www.webcomponents.org/element/PolymerElements/paper-tabs)).

**Comment by equinusocio** [comment]
The way is the composition like `paper-tabs`. Components `oa-tabs` and `oa-tab` should not know the tab content. `oa-tabs` just handle the show/hide of `oa-tab`.
