### ISSUE TITLE
Uncaught TypeError: Cannot read property '__mixinSet' of undefined

### ISSUE THREAD

**Issue by irsooti** [contactlab/contactlab-ui-components#202]
Hello, in advance, great work with the library!

I encountered some issues importing your hybrid  library in version 3.0.0-pre.12.
Client side, the error is like the following: 

![image](https://user-images.githubusercontent.com/7157155/38768775-fb73bcfc-3ff8-11e8-90f5-ff7cb5f61289.png)

In order to avoid the error I've just replaced your original import syntax:

`import { Element as PolymerElement } from '@polymer/polymer/polymer-element';`

in:

`import { PolymerElement } from '@polymer/polymer/polymer-element`

It seems to work properly now, but it might be some side effects?
Thanks

**Comment by moebiusmania** [comment]
hi @irsooti , the error you are reporting is given by the latest update in Polymer 3 pre-release (details here https://www.polymer-project.org/blog/2018-03-23-polymer-3-latest-preview.html ) which have some breaking changes like the import definition. So basically, this library just hasn't been tested with it yet :sunglasses: .

**Comment by StefanoMagrassi** [comment]
closed by #203
