### ISSUE TITLE
DropdownClab: search attribute doesn't work [Polymer 3.0.0.pre12]

### ISSUE THREAD

**Issue by irsooti** [contactlab/contactlab-ui-components#206]
The component doesn't show the dropdown list even if the input matches with an option in array.

![2018-04-17_14-58-02](https://user-images.githubusercontent.com/7157155/38871017-d93cda48-424f-11e8-947c-06d4a6f1d5c0.gif)

I know the library is now [deprecated](https://github.com/contactlab/contactlab-ui-components/blob/master/README.md), but some support is **very** appreciated.

Thank you

**Comment by StefanoMagrassi** [comment]
HI @irsooti, as you said the package is **deprecated** and you are also using the non-stable version of the library.

Sorry, by now we cannot help you...

**Comment by moebiusmania** [comment]
hi @irsooti , unfortunately this was a known bug (referenced in the readme https://github.com/contactlab/contactlab-ui-components/tree/next#notable-changes-from-v14--master-branch ) that I wasn't able to solve at the time... 😭
