### ISSUE TITLE
Autocomplete search needs a valid regExp

### ISSUE THREAD

**Issue by Arual90** [contactlab/contactlab-ui-components#207]
Autocomplete-clab search functionality doesn't work when special characters are used. Es: [, +.

This is because it uses the function `String.prototype.search` which accepts a regExp or a string that can be turned into a RegExp.

```js
const phrase = '[laura] è al mare';

phrase.search('laura') // -> correctly returns the index
phrase.search('[laura') // -> Uncaught SyntaxError: Invalid regular expression
```

'[laura' cannot be turned into a RegExp unless the special character is escaped.

How To Fix:
Escape the string using https://www.npmjs.com/package/escape-string-regexp

**Comment by StefanoMagrassi** [comment]
closed by #208
