### ISSUE TITLE
<dropdown-clab>: altezza elementi e highlight

### ISSUE THREAD

**Issue by moebiusmania** [contactlab/contactlab-ui-components#39]
I metodi che computano l'highlight della voce attuale e l'altezza degli elementi in alcuni casi (testabili su ContactPlan) generano errori che bloccano l'apertura della tendina e quindi l'utilizzo del componente.

Come workaround *temporanei*
- _compHighlight è commentato
- _setMaxHeight imposta un valore fisso di 30px

bisogna identificare i problemi e fixarli in maniera appropriata

**Comment by LasaleFamine** [comment]
- "_compHighlight" è stato sostituito da un altro metodo funzionante "_handleHighlight" che gestisce l'evento del `curtain`

- _setMaxHeight non esiste più: è stata aggiunta una proprieta (pubblica) sia al `dropdown` che al `curtain` (maxHeight): 
``` js
maxHeight: {
    type: Number,
    value: 28
}
```
