### ISSUE TITLE
Test unitari

### ISSUE THREAD

**Issue by moebiusmania** [contactlab/contactlab-ui-components#46]
definire degli Uni Test tramite il Web Component Tester

- [x] test per ogni componente
- [x] suite tests
- [x] azione npm
- [x] update readme

**Comment by LasaleFamine** [comment]
In realtà forse andrebbero rivisti i test dopo la risoluzione di #39 e #45

**Comment by LasaleFamine** [comment]
Test rivisti dopo aver completato #39

**Comment by moebiusmania** [comment]
ci sono dei casi di test dei dom-binding che hanno esiti un po quantistici... motivo per cui eviterei di testarli in quanto feature di Polymer. Per il resto consideriamola chiusa!
