### ISSUE TITLE
Rivedere componente <menu-clab>

### ISSUE THREAD

**Issue by moebiusmania** [contactlab/contactlab-ui-components#48]
- [ ] Componente pubblico (e quindi svariati casi da coprire) o interno(solo i casi che riguardano le applicazioni clab) ?
- [ ] Refactor gestione voci di menu (via JSON e anche via HTML)
- [ ] Selezione link attivo tramite API componente
- [ ] Gestire il secondo livello? integrare il componente del sub menu?
- [ ] Sistemare versione mobile

**Comment by Arual90** [comment]
Io voterei per renderlo un componente interno
