### ISSUE TITLE
dropdown + search

### ISSUE THREAD

**Issue by raoulmeroni-clab** [contactlab/contactlab-ui-components#54]
Bisognerebbe impostare una dropdown con la possibilità di fare la ricerca nei valori

**Comment by moebiusmania** [comment]
Creare un componente che wrappa autocomplete e dropdown (o anche solo il curtain) per ricreare una funzionalità tipo Select2/Chosen, **non** creare nuovo componente ad hoc.

**Comment by moebiusmania** [comment]
Moved to https://github.com/orkestra-elements/orkestra-elements/issues/3 .
