### ISSUE TITLE
<group-clab>: type class computation

### ISSUE THREAD

**Issue by moebiusmania** [contactlab/contactlab-ui-components#66]
The computation of attribute class **type** does not work unless user specify the **size** attribute together.
Maybe related to #49 .

**Comment by LasaleFamine** [comment]
The problem is related to the undefined declaration of the `size` property:
``` js
/**
* `size` additional class for the size of the buttons
*/
size:{
    type: String
    value: '' // this declaration must be present
},
``` 

Working on a PR.
