### ISSUE TITLE
Navbar component?

### ISSUE THREAD

**Issue by giorgioarcella** [contactlab/contactlab-ui-components#71]
Hi! I'm trying the components, and i'd find really useful a responsive navbar component like the one on [the documentation website](https://ux.contactlab.com/#/design/colors). Are you planning to add this?
Thank you!

**Comment by moebiusmania** [comment]
hi, on the [ux.contactlab.com](https://ux.contactlab.com/) website we aren't really using a navbar component, beacuse we started it out some months ago but we haven't defined a **scope** (if can be a public component or just internal, if we have to handle multi level navigations, ecc) so at the moment its just a DOM element. If you really need it you can copy the HTML and CSS from the [sources of the website](https://github.com/contactlab/contactlab-pattern-library).

**Comment by moebiusmania** [comment]
Moved to https://github.com/orkestra-elements/orkestra-elements/issues/2
