### ISSUE TITLE
Set initialValue for calendar-clab

### ISSUE THREAD

**Issue by giorgioarcella** [contactlab/contactlab-ui-components#72]
Hi! Is there a way to set dinamically the current date time in the options object of calendar-clab? I'm trying to use jquery on the $('calendar-clab') element, setting the option object with .attr() function, but doesn't work.
Thank you for the help :)

**Comment by LasaleFamine** [comment]
Hi,
you can set the `value-str` property of the `calendar-clab` element using jQuery.
There is only a simple note to know: when you get the element with the jQuery selector you need to specify that you want to get the first element inside.

I made a jsfiddle as an example: https://jsfiddle.net/j6kfuay8/

Anyway I suggest to use the native `document.querySelector` for getting the element.
Hope it helps!

**Comment by giorgioarcella** [comment]
Sorry, i didn't explain properly my issue: there is an "option" attribute for the calendar-clab component, which must be a "Rome options object" (as written in the documentation); on the Rome object doc, i see that to set an inital datetime i have to give a value to "initialValue" attribute. I'd like to set this with Date.now(), but i can't use javascript code in the declaration of the html component, so i tried to set it via javascript after the document was ready, but didn't work..

**Comment by Arual90** [comment]
Hi, 
As @LasaleFamine said it's better if you use the `value-str` property to set the initial value of the calendar.
`document.querySelector('#calendar').valueStr = initialValue`
Where `initialValue` stores the correct date you need.

PS:
In addition i suggest you use moment.js methods, calendar-clab is already importing the library.
So you could do this:
`document.querySelector('#calendar').valueStr = moment().format('DD-MM-YYYY')`

**Comment by giorgioarcella** [comment]
Thank you @Arual90 !
Now i only have a visual problem: the widget always appears under the input i click...if the input is on the bottom of the page it should appear on the top. Same fot the time widget, which appears always under everything.
Thank you again!

**Comment by moebiusmania** [comment]
hi @giorgioarcella , for the "using with jQuery" part it was already in [roadmap on the documentation site](https://github.com/contactlab/contactlab-pattern-library/issues/22), I will give it priority :-) 

I have created a more specific issue (#73) related to the calendar position, so I'm closing this one, I will get you notified when that issue will be solved!

tnx!
