### ISSUE TITLE
Firefox loading components

### ISSUE THREAD

**Issue by giorgioarcella** [contactlab/contactlab-ui-components#74]
Hi, i used the webcomponents-lite js for my application; testing with firefox, the page loads in a little more time than chrome (3-4 secs), and in this time i can see the html content of the `modal-clab` that i placed at the bottom of the page..after the loading it disappears, and the modal starts working as expected. 
Is there a way to hide it until the script (and so the behavior of the component) is loaded? If i use a css like `display:none `it remains hidden even while i call the `show()` method..

**Comment by moebiusmania** [comment]
hi, these behaviors you are reporting are not related to the project itself but are more generics to Javascript & WebComponents 😉 

To explain quickly:

1. **Firefox loading time**: Firefox does not (still) fully supports the Web Components specification as opposite of Chrome, so it has to be patched on runtime by the polyfill and this take some time. You can [read here](https://www.polymer-project.org/1.0/docs/browsers) for more info.

2. **Flashing of content in Web Components**: is a strict consequence of the above.

3. **(Fake) preloading techniques**: to prevent the flashing of content you may use some techniques of preloading, there are various solutions, if you need something quickly you can borrow t[he one we used on the Pattern Library Website](https://github.com/contactlab/contactlab-pattern-library/blob/master/app/index.html) , where we have a pure HTML spinner (using the same CSS of the spinner component, so you have it for free) and we remove that when the Web Components are ready using the ``` WebComponentsReady  ``` event on the window object.

**Comment by giorgioarcella** [comment]
Grazie mille!! Mi serviva la info sull'evento WebComponentsReady, ora sono a posto ;)
