### ISSUE TITLE
de-Gulpify development actions

### ISSUE THREAD

**Issue by moebiusmania** [contactlab/contactlab-ui-components#80]
We are moving all of the development tasks to "pure" NPM scripts rather than Gulp wrappers.

so this
``` $ gulp dev ``` 
will become something like
``` $ npm run dev ``` or ``` $ yarn run dev ```

**Comment by LasaleFamine** [comment]
This incorporates also the issue #79 about the "no-polymer" build.

**Comment by LasaleFamine** [comment]
`develop` branch with new ***de-gulpify*** build (with and without Polymer) tested.

I think it's ready to be merged into `master`

cc: @moebiusmania
