### ISSUE TITLE
Move icon-fonts in a separate project/repo

### ISSUE THREAD

**Issue by moebiusmania** [contactlab/contactlab-ui-components#89]
The icons ( https://ux.contactlab.com/#/design/iconography ) should be available without downloading all the web components of this library, since they are pure CSS+font.

Moving them in a new repo will give more **flexibility** on how to use the Contactlab Pattern Library and will not require this repo to trigger a release workflow for minor changes.

@Arual90 @LasaleFamine @pasuslab @pferretti @psantori suggestions for the name?

**Comment by pferretti** [comment]
contactlab-ui-icons
contactlab-icons-awesome

**Comment by moebiusmania** [comment]
**ikonograph** (helped by Carlo 😄  )

**Comment by equinusocio** [comment]
**contactlab-icons**
- contactlab-uicons
- contactlab-sprite-icons
- clab-icons
